<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/11/28 17:14:07

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=hrmtwins_oran862',
  'username' => 'hrmtwins_oran862',
  'password' => 'p(4Sz(5s44',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
